### ISSUE TITLE
Problem with seeing money saved etc

### ISSUE THREAD

**Issue by pigeon7i** [scoute-dich/QuitSmoking#1]
https://lut.im/3P5EU53cRT/UMY1y4icgygZawoh

**Comment by scoute-dich** [comment]
You set the wrong date. You chose German date format (day month year). Please chose the international date format (month day year) in settings. Report back of this solves the problem. Thanks.

**Comment by scoute-dich** [comment]
I mean international (year month day).

**Comment by pigeon7i** [comment]
I know, doesn't change anything, number are still cutted out - https://lut.im/z5hbsDF5sA/ak1rH2hmw0f8CjWt and I can't scroll down more to see them whole.

**Comment by scoute-dich** [comment]
Ok, I'll take a look these days.

**Comment by scoute-dich** [comment]
What's your screen size and resolution?

**Comment by pigeon7i** [comment]
5 inches HD

**Comment by scoute-dich** [comment]
Hi,

I atatched an apk within the Zip-file. Perhaps you can test it and report back, before I will release an update?

Thanks in advance.

Gaukler Faun
[app-release.zip](https://github.com/scoute-dich/QuitSmoking/files/405653/app-release.zip)

**Comment by pigeon7i** [comment]
https://lut.im/j4WZ4Ad2jH/wqMrnSwNLxPzDdb8 - yep

**Comment by scoute-dich** [comment]
Ok, update is on his way. Thanks for your help.
