### ISSUE TITLE
Not correct saved time

### ISSUE THREAD

**Issue by konkor** [scoute-dich/QuitSmoking#11]
The app shows saved time in Hours but in the settings tab it asked for minutes! For all cigarettes or just time for one?!
Nice app)
PS: Is it possible to show some tips to quit or something?

**Comment by scoute-dich** [comment]
, in the settings you have to enter the time for one cigarette in minutes. The overview tab shows the saved time I'm hours. Dies it work correctly?

**Comment by konkor** [comment]
1. Now if I enter only average count cigarettes per day. Saved time doesn't show any saved time just 0h.
2. If I enter 1 'minutes'  and count cigarettes I have on the main screen like 52 cigarettes X.xx$ 52.0 h. But I expected 52*1/60 ~0.9 h

**Comment by scoute-dich** [comment]
Btw. Are we talking about "not smoked since" or the saved time value in the last line?

**Comment by konkor** [comment]
Last line last value saved time

**Comment by scoute-dich** [comment]
For me it is working. Are you on the latest version? Can you please attach screenshots?

**Comment by konkor** [comment]
I have Smoke habits - time in minutes 1 value
And saved time for 35 cigarettes 35 hours. Is it OK?

**Comment by scoute-dich** [comment]
Yea, now I can reproduce the bug. You are using international date format. I will try to fix it.

**Comment by konkor** [comment]
TY)

**Comment by scoute-dich** [comment]
I have fixed it. Thanks for your patience. Tomorrow I will implement a date-time picker in the settings and then I will release the update.

Regards
Gaukler Faun
