### ISSUE TITLE
Reset button (fail button)

### ISSUE THREAD

**Issue by bas080** [scoute-dich/QuitSmoking#12]
Reseting last smoked time is hard. It'd be nice to have a reset button that resets the last smoked time, and shows a stats page on how you did compared to previous smoking brakes.

# Details
- show last 5 durations in minutes between cigarettes (maybe chart)
- a recap of what you have achieved. (The health achievements in a row).
- the next achievement you should try to reach in your next try

**Comment by scoute-dich** [comment]
You can just enter a new start time in the settings. And if you like to have an overview about smoke breaks you can create a note.

I think I could implement a reset button. And clicking it would rest the time and automatically create a note with time, date, ...

Would this also benefit your suggestion?

**Comment by bas080** [comment]
That would help me a lot

**Comment by scoute-dich** [comment]
Ok, then it is on my todo list. But in the next days I haven't much time. So you must wait alittle bit...

**Comment by scoute-dich** [comment]
I've implemented it. This feature will be available with next update.
