### ISSUE TITLE
Wrong chart in the Health tab

### ISSUE THREAD

**Issue by Primokorn** [scoute-dich/QuitSmoking#14]
Hi,
As you can see in the screenshot below, all charts are full (or empty I don't remember the color code :)).
Version 2.4 but I can't say if it happened since this version or an older one.

![capture](https://cloud.githubusercontent.com/assets/5938828/26726948/3620d7ce-47a5-11e7-8acb-b3e2adefba53.PNG)

**Comment by scoute-dich** [comment]
No issues here... Perhaps it solves the problem, when you edit the start time in the settings. Some things got messed, when I implemented the date picker... Can you please test?

**Comment by Primokorn** [comment]
Sorry buddy it's actually related to the Substratum theme I use (Pitch Black).
