### ISSUE TITLE
Error in the original strings

### ISSUE THREAD

**Issue by Primokorn** [scoute-dich/QuitSmoking#16]
` <string name="health_description7">The entire blood circulation improves. The increased lung capacity
         by up to 30 \%, they can absorb more oxygen again. This increases the physical
         Performance. (3 months)</string>`

The sign **%** doesn't appear in the app:
![screenshot_20170616-082309](https://user-images.githubusercontent.com/5938828/27214533-5a2c8924-526d-11e7-9977-07b823c63c3e.png)

Can we simply remove `\`?

**Comment by scoute-dich** [comment]
Yes, we can. I did it for all languages. Thanks for reporting. Will be fixed with next update.
