### ISSUE TITLE
[Feature request] Several periods of price

### ISSUE THREAD

**Issue by Primokorn** [scoute-dich/QuitSmoking#17]
Hi,
The price of cigarettes will increase in France next year. To get a better idea of the money I saved it would be great to have several fields for prices which are linked to a period of time.

Example:
1. From 01/01/2016 to 31/12/2016 => cost of one cigarette: 0.20 EUR
2. Starting from 01/01/2017 => cost of one cigarette: 0.23 EUR

Number of cigarettes per day: 10
Number of days per year: 365

1. 365 days * 2 year * 2 EUR = 1 460 EUR
2. _(Up to now)_  187 days * 2.30 EUR = 430 EUR
Total of saved money = 1 890 EUR

Thank you.

**Comment by scoute-dich** [comment]
I think we can solve the problem within this year...

_Gesendet von meinem OnePlus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Primokorn** [comment]
Forget this request if it's too complicated.
I'm gonna use LibreOffice Calc.

**Comment by mesnevi** [comment]
Quit attempt takes pretty short period of time, thus I consider adding different prices for cigarettes an over-complication.
