### ISSUE TITLE
Source of information

### ISSUE THREAD

**Issue by airon90** [scoute-dich/QuitSmoking#18]
Hi, where did you get the information about health and their targets?

**Comment by scoute-dich** [comment]
http://www.onmeda.de/rauchen/rauchfrei.html

The sources of the above mentioned website are:

- Online-Informationen der American Cancer Society: www.cancer.org (31.01.2011)

- Online-Informationen des Bundeszentrale für gesundheitliche Aufklärung (BZgA): www.rauchfrei-info.de (Stand: 2010)

- Online-Informationen der Deutschen Hauptstelle für Suchtfragen e.V. (DHS): www.dhs.de (Stand: 2007)
