### ISSUE TITLE
About License and redistribution

### ISSUE THREAD

**Issue by DineshNeupane** [scoute-dich/QuitSmoking#20]
I just wanted to know if I can use the source code for my project and redistribute it (after modification)  mentioning the source in About page.

**Comment by scoute-dich** [comment]
That's possible, if you also use the gpl license (or similar) and if you also make your code public.

**Comment by DineshNeupane** [comment]
I was not clear about the GPL licensing terms so I asked you. Anyways, thank you.

**Comment by scoute-dich** [comment]
You're welcome. That's the power of free software: grab the code, improve it and release it as free software too.

My I ask, what modifications do you plan? Because it's also possible to contribute on my browser.

**Comment by DineshNeupane** [comment]
like the design is too bad. i was planning to add some features to distract the smokers like pressing bubble game or something like that.. no worries, now i will do the whole by myself.

**Comment by mesnevi** [comment]
This is the design I like the most in this very app! It's simple and has no redundant details and features (such as in-app games, ads and links to other apps). Colors are great, too, and even "Health" tab is worth reading at least once. 

I improved the icon (in my view, the one used at the moment pictures 'no smoking in this area'. The one meaning 'stop smoking' would rather use broken cigarette or crumpled cigarette stub. I'm also going to add some more currency to the list. I love this decent app, though I use it for intermittent fasting tracking, not quitting smoking.
