### ISSUE TITLE
Health tab: "reached in:" is false in days (french translation)

### ISSUE THREAD

**Issue by issueseverywhere** [scoute-dich/QuitSmoking#26]
Hello!

I don't know if it is the app or the french translation, but for the health goals reached after one day at least, the count down of the first day (24h) doesn't happen.

For example, the 3rd health item, infarctus, after 5 minutes of not smoking, shows: "reached in 1 day 23h 55 minutes", although its description says (1 day) so it is supposed to be reached in 24h 55 minutes after 5 minutes not smoking.

One could argue that we should just forget that 1 day  inacuracy but psychologically it is quite demoralizing  to see this once you reached the 2 first health goals!

Really thank you for the app!
Been using it for a week, i didn't stop smoking yet but now i look at the app when i want to smoke and it makes me last a few hours more before the next cigarette. Really hope i'll get to stop!

**Comment by mesnevi** [comment]
Seems the app is bugged, not the FR translation. I'll check things out a bit later. Actually, I feel totally the same you described, I don't stop failing main targets (I use the app for intermittent fasting tracking, not for smoking issues), but it definitely helps to straighten things up noticeably.
