### ISSUE TITLE
App keeps telling me to "Configure in settings"

### ISSUE THREAD

**Issue by sputtene** [scoute-dich/QuitSmoking#3]
Hi,

I've filled out the date and time I smoked my last cigarette, but instead of some statistics, the Overview screen shows me a lot of "Configure in settings".

I use international date format, if that matters.
I had to enter 2300 as the time, because the numerical keyboard that popped up to enter the time doesn't have a :Since I don't get any error messages, I assume what I entered is correct.

Let me know if you want some screenshots, a logcat or other further info.

Thanks!

**Comment by scoute-dich** [comment]
The time format is not correct. It must be entered with ":". What keyboard are you using?

**Comment by sputtene** [comment]
Hacker's keyboard.

After switching to the stock Android keyboard, it works :)

**Comment by scoute-dich** [comment]
Ok.
