### ISSUE TITLE
App posted on Google Play, does not mention location of source

### ISSUE THREAD

**Issue by brarcher** [scoute-dich/QuitSmoking#6]
I noticed on the Google Play store that a quit smoking application with your same application ID, namely de.baumann.quitsmoking, is posted under the author Jolly Crab Studios.

https://play.google.com/store/apps/details?id=de.baumann.quitsmoking

I suspect that you did not authorize this developer to publish your work under their name, especially in violation of the GPLv3 as no link to the source code is provided. This developer did the same with another of my applications.

If you are interested, you may choose to ask Google to take down this application, if that is your wish.

https://support.google.com/legal/contact/lr_dmca?product=googleplay

FYI.

**Comment by scoute-dich** [comment]
Thanks for reporting. It seems, that in the meantime all their apps are removed from the playstore. But I found some of my other apps also in the playstore...

**Comment by brarcher** [comment]
I reported the apps that I found of mine taken by others and Google responded by taking down the apps. I found your app because the same developer had taken one of my app, and has a suspiciously large catalog of applications each with a vastly different application id. The developer responsible may have also had their accounts deactivated, if it was found they are repeat offenders.

Anyway, if you find other applications being taken, feel free to open a DMCA notice with Google (link mentioned earlier). If you see other applications being taken from other GitHub users, maybe also let them know. (:

**Comment by scoute-dich** [comment]
Ok. I will make it so. Today I reported some apps. I will wait now and look what happens. How long did it take till the reported apps were removed?

**Comment by brarcher** [comment]
For two apps they were removed within two days. For a third Google requested additional information and the investigation is ongoing for about a week now.

On March 10, 2017 2:43:46 PM EST, Gaukler Faun <notifications@github.com> wrote:
>Ok. I will make it so. Today I reported some apps. I will wait now and
>look what happens. How long did it take till the reported apps were
>removed?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scoute-dich/QuitSmoking/issues/6#issuecomment-285765908

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Poussinou** [comment]
@scoute-dich Hi, I assume there is another problem [here with this app](https://play.google.com/store/apps/details?id=free.QuitSmoking.Tracker)...

Are the others apps you reported in March taken down?

**Comment by scoute-dich** [comment]
Thanks for reporting. Yes, they were taken down...

Google doesn't allow the user install apps from untrusted sources. But the more articles I read about apps which steal user data on PlayStore and the more stolen apps I see on PlayStore, I must ask: "Is the PlayStore a secure source?".

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scoute-dich** [comment]
I I'll report this apps also. And I will publish my app on PlayStore to give uses the original, without useless permissions and ads...

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Poussinou** [comment]
Google allows the user to install apps from untrusted sources, but you have to activate this option, disabled per default.

Google Play is not that secure, no... And there are many many many open source apps that are on the Play Store, without the permission of the author (like you), and without source code and open source licenses... (Have a look at the different issues i opened this week...)
Thanks for reporting them.

**Comment by scoute-dich** [comment]
Yes, with enabling untrusted sources I know. The other point: that's the reason, why I don't close that issue.

Thanks again for reporting.

_Gesendet von meinem Oneplus A0001 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Poussinou** [comment]
No problem

**Comment by Poussinou** [comment]
@scoute-dich Another one [here](https://www.amazon.fr/Drivio-Developers-Quit-Smoking/dp/B073YHN91L/ref=sr_1_2?s=mobile-apps&ie=UTF8&qid=1502440337&sr=1-2) on the Amazon Store
You can make a request [here](https://www.amazon.com/gp/help/reports/infringement) to remove it

**Comment by mesnevi** [comment]
So, people steal the code without even modifying or changing packages names. It's sad, annoying, and frustrating. How do we usually treat cheaters? We avoid them. Let everyone show their own judgment in deciding which way of making money is  good enough.
